### ISSUE TITLE
csrf token is not rendered in TurboStream Responses

### ISSUE THREAD

**Issue by JulianFeinauer** [rails-inspire-django/django-turbo-helper#11]
If you render a Form containing `{% csrf_token %}` it is not rendered.

This is related to this issue: https://stackoverflow.com/questions/34629261/django-render-to-string-ignores-csrf-token

**Comment by chrisgrande** [comment]
I'm not seeing this, are you adding the request to `.response()` when you return the `TurboStream`, like so `.response(request=request)`. 

The docs just have `.response(request)`, I updated [via a pull request](https://github.com/hotwire-django/django-turbo-response/pull/10) but the rendered docs don't seem to have updated.

**Comment by JulianFeinauer** [comment]
Thanks @chrisgrande, indeed i didn't update the docs and i tried to pass the request via kwargs but it didn't work for me... Strange

**Comment by danjac** [comment]
`.response(request=request)` indeed should work (I've added a couple tests to confirm). Perhaps @JulianFeinauer if you could provide more context for what you are doing?

**Comment by JulianFeinauer** [comment]
@danjac and @chrisgrande you both are right. I tried it again and it works. No idea what I did wrong initially.
So we can either keep it as is to have the request more explicit as variable or close this PR. Its up to you : )
